package com.aplusscore.android.rtsp

import android.media.MediaExtractor
import android.media.MediaFormat
import android.media.MediaMuxer
import android.media.MediaCodec
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.io.File
import java.nio.ByteBuffer
import java.util.concurrent.atomic.AtomicBoolean

class RtspSegmentRecorderModule(
  private val reactContext: ReactApplicationContext,
) : ReactContextBaseJavaModule(reactContext) {
  @Volatile private var running = false
  @Volatile private var worker: Thread? = null
  @Volatile private var extractor: MediaExtractor? = null
  @Volatile private var muxer: MediaMuxer? = null
  @Volatile private var currentOutputPath: String? = null
  @Volatile private var lastError: String? = null

  override fun getName(): String = "RtspSegmentRecorder"

  @ReactMethod
  fun isRecording(promise: Promise) {
    promise.resolve(running)
  }

  @ReactMethod
  @Synchronized
  fun start(rtspUrl: String, outputPath: String, promise: Promise) {
    if (running) {
      promise.resolve(true)
      return
    }

    val url = rtspUrl.trim()
    val out = outputPath.trim()
    if (!url.startsWith("rtsp://", ignoreCase = true)) {
      promise.resolve(false)
      return
    }
    if (out.isEmpty()) {
      promise.resolve(false)
      return
    }

    try {
      File(out).parentFile?.mkdirs()
    } catch (_: Throwable) {}

    val started = AtomicBoolean(false)
    val resolved = AtomicBoolean(false)
    running = true
    currentOutputPath = out
    lastError = null

    val thread = Thread({
      var localExtractor: MediaExtractor? = null
      var localMuxer: MediaMuxer? = null
      var muxerStarted = false

      fun resolveOnce(value: Boolean) {
        if (resolved.compareAndSet(false, true)) {
          try {
            promise.resolve(value)
          } catch (_: Throwable) {}
        }
      }

      try {
        localExtractor = MediaExtractor()
        extractor = localExtractor

        // RTSP credentials are already embedded in the URL generated by JS.
        localExtractor.setDataSource(url, HashMap<String, String>())

        val trackCount = localExtractor.trackCount
        val sourceToMuxerTrack = HashMap<Int, Int>()
        localMuxer = MediaMuxer(out, MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4)
        muxer = localMuxer

        var selectedVideo = false
        for (i in 0 until trackCount) {
          val format = localExtractor.getTrackFormat(i)
          val mime = format.getString(MediaFormat.KEY_MIME) ?: ""
          if (mime.startsWith("video/") || mime.startsWith("audio/")) {
            try {
              val muxerTrack = localMuxer.addTrack(format)
              sourceToMuxerTrack[i] = muxerTrack
              localExtractor.selectTrack(i)
              if (mime.startsWith("video/")) {
                selectedVideo = true
              }
            } catch (_: Throwable) {
              // Some live RTSP streams expose tracks Android's muxer cannot add.
              // Ignore those tracks but keep any usable video track.
            }
          }
        }

        if (!selectedVideo || sourceToMuxerTrack.isEmpty()) {
          lastError = "No muxable video track found in RTSP stream"
          running = false
          resolveOnce(false)
          return@Thread
        }

        localMuxer.start()
        muxerStarted = true
        started.set(true)
        resolveOnce(true)

        val bufferSize = 2 * 1024 * 1024
        val buffer = ByteBuffer.allocateDirect(bufferSize)
        val info = MediaCodec.BufferInfo()
        val firstPtsByTrack = HashMap<Int, Long>()

        while (running) {
          buffer.clear()
          val sampleSize = try {
            localExtractor.readSampleData(buffer, 0)
          } catch (readError: Throwable) {
            if (running) {
              lastError = readError.message ?: readError.toString()
            }
            break
          }

          if (sampleSize < 0) {
            Thread.sleep(20)
            continue
          }

          val sourceTrack = localExtractor.sampleTrackIndex
          val muxerTrack = sourceToMuxerTrack[sourceTrack]
          if (muxerTrack != null) {
            val rawPts = localExtractor.sampleTime.coerceAtLeast(0L)
            val firstPts = firstPtsByTrack.getOrPut(sourceTrack) { rawPts }
            info.set(
              0,
              sampleSize,
              (rawPts - firstPts).coerceAtLeast(0L),
              localExtractor.sampleFlags,
            )
            try {
              localMuxer.writeSampleData(muxerTrack, buffer, info)
            } catch (writeError: Throwable) {
              if (running) {
                lastError = writeError.message ?: writeError.toString()
              }
              break
            }
          }

          try {
            if (!localExtractor.advance()) {
              Thread.sleep(10)
            }
          } catch (_: Throwable) {
            break
          }
        }
      } catch (error: Throwable) {
        lastError = error.message ?: error.toString()
        if (!started.get()) {
          resolveOnce(false)
        }
      } finally {
        running = false
        extractor = null
        muxer = null

        try {
          localExtractor?.release()
        } catch (_: Throwable) {}

        if (muxerStarted) {
          try {
            localMuxer?.stop()
          } catch (_: Throwable) {}
        }
        try {
          localMuxer?.release()
        } catch (_: Throwable) {}

        if (!resolved.get()) {
          resolveOnce(started.get())
        }
      }
    }, "AplusRtspSegmentRecorder")

    worker = thread
    thread.start()
  }

  @ReactMethod
  @Synchronized
  fun stop(promise: Promise) {
    val out = currentOutputPath
    running = false

    // Releasing extractor helps unblock readSampleData on some RTSP streams.
    try {
      extractor?.release()
    } catch (_: Throwable) {}

    try {
      worker?.join(3500)
    } catch (_: Throwable) {}

    worker = null
    extractor = null
    muxer = null

    val usablePath = try {
      if (!out.isNullOrBlank()) {
        val file = File(out)
        if (file.exists() && file.length() >= 128 * 1024) out else null
      } else {
        null
      }
    } catch (_: Throwable) {
      null
    }

    currentOutputPath = null
    promise.resolve(usablePath)
  }

  @ReactMethod
  fun getLastError(promise: Promise) {
    promise.resolve(lastError)
  }
}
